### PR TITLE
Update version to 1.5.5

### PR DESCRIPTION
**Pull request by seitenbau-govdata**
Since the last version had still a bug in displaying the last job error summary we would like to release a new version `1.5.5`.

### CODE REVIEW

**Comment by seitenbau-govdata** [comment]
@amercader or @pdelboca  We would like to release a new version with the latest fixes for the last job error summary display. Could you have a look at the PR and if looks good merge it and create a new tag? Thanks in advance!

**Comment by amercader** [comment]
Done @seitenbau-govdata 

Would you like to help maintain this extension as you are already doing with ckanext-dcat?

**Comment by seitenbau-govdata** [comment]
@amercader Sure, gladly. Thanks for the offer.

**Comment by amercader** [comment]
You should have write access now @seitenbau-govdata, thanks for the help

**Pull request merged**
