### PR TITLE
Fix harvest request exceptions

### PR DESCRIPTION
**Pull request by kentsanggds**
We are currently getting a error AttributeError: `SSLError` object has no attribute `code`. 
This changes the harvest exception handling so we can correctly log the error.

### CODE REVIEW

**Comment by metaodi** [comment]
Ah I see there is a CI error because of an unrelated import of new_test, I'll take care of it.

**Comment by kentsanggds** [comment]
@metaodi cheers!

**Comment by kentsanggds** [comment]
Found a bug, will deploy a new fix with tests

**Comment by kentsanggds** [comment]
Will spin up another PR with the fix and tests

**Pull request closed without merging**
