### PR TITLE
Fix deprecated nav_named_link

### PR DESCRIPTION
**Pull request by davidread**
h.nav_named_link appears to have been removed 2 weeks ago with https://github.com/ckan/ckan/pull/2908

There was a previous effort to replace nav_named_link: https://github.com/ckan/ckanext-harvest/pull/224/files but it appears to have missed this one template.

### CODE REVIEW

**Comment by davidread** [comment]
Note this bug was the reason for this Q: http://stackoverflow.com/questions/36767847/ckan-harvester-nav-named-link-error

**Comment by davidread** [comment]
@amercader would you mind merging this?

**Comment by amercader** [comment]
cheers @davidread

**Comment by TkTech** [comment]
@davidread Thanks, I thought I had caught every usage of it but I seem to have missed one!

**Pull request merged**
