### PR TITLE
Run jobs straight away.

### LINKED ISSUE #111: Run jobs straight away
When you create a harvester it is a problem that the harvest doesn't run straight away. You have to wait up to 15 minutes for the 'harvester run' cron to run. This means you do something else and often forget to attend to it again for hours. This makes fixing issues with the harvest source a painfully slow process.

I believe that the reason there the harvests are spaced by 15 minutes in the original design was because of the fear that a harvest source could get run twice in parallel, and get in a mess. Recently @amercader added into the 'harvest run' a check to see if a job has finished. Since this is now recorded we do not need to wait for the 15 minute cron - we can start a job when it is created, in the knowledge that a job can't start until the previous one for the source has completed. This simply means putting the job on the gather queue straight away. 'harvest run' will still be used for running scheduled jobs.

### PR DESCRIPTION
**Pull request by davidread**
Fixes #111

### CODE REVIEW

**Comment by neothemachine** [comment]
Just tried it out, but it only worked half-way. After pressing "reharvest" in the web interface it immediately started the job, but it didn't finish it. In the console I manually ran "run" and that did finish it.

**Comment by neothemachine** [comment]
Debug output:
```
2015-10-28 22:44:51,471 INFO  [ckanext.harvest.logic.action.update] Harvest job run: {}
2015-10-28 22:44:51,499 INFO  [ckanext.harvest.logic.action.update] Marking job as finished: <HarvestJob id=f40057eb-a563-4dd3-abf5-86920ffdf658 created=2015-10-28 22:43:30.772163 gather_started=2015-10-28 22:43:30.817900 gather_finished=2015-10-28 22:43:35.273987 finished=2015-10-28 22:43:35.654636 source_id=041fbcb6-fb0d-4488-bbaa-b5baa674fe8e status=Finished>
```

So it seems it just wasn't marked as finished but otherwise was already done.

**Comment by davidread** [comment]
That's cool, you still have to do 'run' as a cron job to mark things as finished. Will have to fix that part another day... Thanks for testing!

**Comment by davidread** [comment]
Conflicts are now sorted - ready to review @amercader

**Comment by davidread** [comment]
Ace! Thanks

**Pull request merged**
