### PR TITLE
[WIP] Use verbose mode to analyze build errors

### LINKED ISSUE #369: `test_default_extras` is broken
Using the current ckan `master` the following test is broken:

https://github.com/ckan/ckanext-harvest/blob/ecf578648bee3488f901ba359eaec15209daedfc/ckanext/harvest/tests/harvesters/test_ckanharvester.py#L306-L329

I need to further analyze this and already opened a WIP PR #368.

Any help is appreciated (cc @amercader)

### PR DESCRIPTION
**Pull request by metaodi**
Fixes #369

### CODE REVIEW

**Comment by seitenbau-govdata** [comment]
@metaodi You have to add the parameter `-s` to the nosetests call in bin/travis-run.sh to activate showing the log output. ;-)

**Comment by metaodi** [comment]
@seitenbau-govdata THANK YOU! Omg, I was getting crazy here 😉

**Comment by seitenbau-govdata** [comment]
@metaodi I think the pull request is obsolet now and can be closed.

**Comment by seitenbau-govdata** [comment]
@metaodi Ping! If you will find a little time please close the pull request. Thanks. 😉

**Pull request closed without merging**
