### PR TITLE
Readme test tip ckan parameter

### PR DESCRIPTION
**Pull request by davidread**
L800 is the key addition.

The rest is formatting improvements, which I've tested look better when viewed on github.com.

### CODE REVIEW

**Comment by davidread** [comment]
Cheers @metaodi :)

**Comment by rossjones** [comment]
Is someone able to merge this? Would be a shame after it's been approved to risk it needing a rebase at some point :)

**Comment by metaodi** [comment]
@rossjones of course :wink:

**Comment by davidread** [comment]
Oops, sorry I forgot to press the button. Thanks both!

**Pull request merged**
